/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/editor_deprecated/braces`; params?: Router.UnknownInputParams; } | { pathname: `/../components/editor_deprecated/CodeEditor`; params?: Router.UnknownInputParams; } | { pathname: `/../components/editor_deprecated/indentation`; params?: Router.UnknownInputParams; } | { pathname: `/../components/editor_deprecated/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/editor_deprecated/languages`; params?: Router.UnknownInputParams; } | { pathname: `/../components/editor_deprecated/strings`; params?: Router.UnknownInputParams; } | { pathname: `/../components/editor_deprecated/SyntaxHighlighter`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/open` | `/open`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/options` | `/options`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/test` | `/test`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../components/editor_deprecated/braces`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/editor_deprecated/CodeEditor`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/editor_deprecated/indentation`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/editor_deprecated/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/editor_deprecated/languages`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/editor_deprecated/strings`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/editor_deprecated/SyntaxHighlighter`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/open` | `/open`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/options` | `/options`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/test` | `/test`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/../components/editor_deprecated/braces${`?${string}` | `#${string}` | ''}` | `/../components/editor_deprecated/CodeEditor${`?${string}` | `#${string}` | ''}` | `/../components/editor_deprecated/indentation${`?${string}` | `#${string}` | ''}` | `/../components/editor_deprecated/index${`?${string}` | `#${string}` | ''}` | `/../components/editor_deprecated/languages${`?${string}` | `#${string}` | ''}` | `/../components/editor_deprecated/strings${`?${string}` | `#${string}` | ''}` | `/../components/editor_deprecated/SyntaxHighlighter${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/open${`?${string}` | `#${string}` | ''}` | `/open${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/options${`?${string}` | `#${string}` | ''}` | `/options${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/test${`?${string}` | `#${string}` | ''}` | `/test${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/editor_deprecated/braces`; params?: Router.UnknownInputParams; } | { pathname: `/../components/editor_deprecated/CodeEditor`; params?: Router.UnknownInputParams; } | { pathname: `/../components/editor_deprecated/indentation`; params?: Router.UnknownInputParams; } | { pathname: `/../components/editor_deprecated/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/editor_deprecated/languages`; params?: Router.UnknownInputParams; } | { pathname: `/../components/editor_deprecated/strings`; params?: Router.UnknownInputParams; } | { pathname: `/../components/editor_deprecated/SyntaxHighlighter`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/open` | `/open`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/options` | `/options`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/test` | `/test`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
